# Generated by Django 4.2.24 on 2025-11-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPrincipal',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cuenta Principal',
                'verbose_name_plural': 'Cuentas Principales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Enero 2025' o 'Año 2025'", max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
            ],
            options={
                'verbose_name': 'Período Contable',
                'verbose_name_plural': 'Períodos Contables',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('periodo', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='sic_webapp.periodocontable')),
            ],
            options={
                'verbose_name': 'Transacción Contable',
                'verbose_name_plural': 'Transacciones Contables',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cuenta_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas_set', to='sic_webapp.cuentaprincipal', verbose_name='Cuenta de Agrupación')),
            ],
            options={
                'verbose_name': 'Subcuenta Contable',
                'verbose_name_plural': 'Subcuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Debe', 'Débito / Cargo'), ('Haber', 'Crédito / Abono')], max_length=5)),
                ('tipo_registro', models.CharField(choices=[('NORMAL', 'Operación Diaria'), ('AJUSTE', 'Asiento de Ajuste (Depreciación, etc.)'), ('CIERRE', 'Asiento de Cierre de Cuentas Nominales')], default='NORMAL', max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subcuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sic_webapp.subcuenta')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='sic_webapp.transaccion')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'ordering': ['transaccion__fecha'],
            },
        ),
    ]
