# Generated by Django 4.2.24 on 2025-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_registro',
            field=models.CharField(choices=[('NORMAL', 'Operación Diaria'), ('AJUSTE', 'Asiento de Ajuste (Depreciación, etc.)'), ('CIERRE', 'Asiento de Cierre de Cuentas Nominales'), ('APERTURA', 'Asiento de Apertura (Saldos Iniciales)')], default='NORMAL', max_length=10),
        ),
    ]
